# Generated by Django 5.0.3 on 2024-03-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alunos", "0003_alter_aluno_turma"),
        ("anos_letivos", "0003_alter_anoletivo_fim_alter_anoletivo_inicio"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_matricula", models.DateField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alunos.aluno"
                    ),
                ),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anos_letivos.anoletivo",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="turmas.turma"
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "turma", "ano_letivo")},
            },
        ),
    ]
