# Generated by Django 5.0.3 on 2024-03-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professores", "0003_rename_disciplina_professor_disc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="data_de_nasc",
            field=models.DateField(null=True, verbose_name="Data de nascimento"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="disc",
            field=models.CharField(max_length=30, null=True, verbose_name="Disciplina"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="nome",
            field=models.CharField(max_length=80, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="telef",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone"
            ),
        ),
    ]
