# Generated by Django 5.0.3 on 2024-03-16 10:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mainmenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menucode", models.IntegerField()),
                ("menuname", models.CharField(max_length=100)),
                ("menutype", models.IntegerField()),
            ],
            managers=[
                ("mainmenulist_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MenuList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Menucode", models.IntegerField()),
                ("MenuType", models.IntegerField()),
                ("menuname", models.CharField(max_length=100)),
                ("submenuname", models.CharField(max_length=100)),
                ("menulink", models.CharField(max_length=100)),
            ],
            managers=[
                ("menulist_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
