# Generated by Django 5.0.3 on 2024-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trimestre", models.CharField(max_length=15)),
                ("inicioT", models.CharField(max_length=15)),
                ("fimT", models.CharField(max_length=15)),
                ("anoletivo", models.CharField(max_length=4)),
            ],
        ),
    ]
