# Generated by Django 5.0.3 on 2024-03-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trimestres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trimestre",
            name="trimestre",
            field=models.CharField(
                choices=[
                    ("IºT", "1ºTrimestre"),
                    ("IIºT", "2ºTrimestre"),
                    ("IIIºT", "3ºTrimestre"),
                    ("EXA", "Exame"),
                    ("REC", "Recurso"),
                ],
                max_length=15,
            ),
        ),
    ]
