# Generated by Django 5.0.3 on 2024-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trimestres", "0002_alter_trimestre_trimestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trimestre",
            name="trimestre",
            field=models.CharField(
                choices=[
                    ("1ºTrimestre", "1ºTrimestre"),
                    ("2ºTrimestre", "2ºTrimestre"),
                    ("3ºTrimestre", "3ºTrimestre"),
                    ("Exame", "Exame"),
                    ("Recurso", "Recurso"),
                ],
                max_length=15,
            ),
        ),
    ]
