# Generated by Django 4.2.11 on 2024-03-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0006_remove_anoletivo_trimestre"),
        (
            "trimestres",
            "0004_remove_trimestre_anoletivo_remove_trimestre_fimt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trimestre",
            name="ano_letivo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anos_letivos.anoletivo",
            ),
        ),
    ]
