# Generated by Django 5.0.3 on 2024-03-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disciplinas", "0001_initial"),
        ("professores", "0003_rename_disciplina_professor_disc"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="professor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="professores.professor",
            ),
        ),
    ]
