# Generated by Django 5.0.3 on 2024-03-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("M", "Matutino"),
                            ("V", "Vespertino"),
                            ("N", "Noturno"),
                        ],
                        max_length=15,
                    ),
                ),
                ("inicio", models.CharField(max_length=3)),
                ("termina", models.CharField(max_length=3)),
            ],
        ),
    ]
