# Generated by Django 5.0.3 on 2024-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periodos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodo",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Matutino", "Matutino"),
                    ("Vespertino", "Vespertino"),
                    ("Noturno", "Noturno"),
                ],
                max_length=15,
            ),
        ),
    ]
