# Generated by Django 5.0.3 on 2024-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periodos", "0002_alter_periodo_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodo",
            name="inicio",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="periodo",
            name="termina",
            field=models.CharField(max_length=10),
        ),
    ]
