# Generated by Django 5.0.3 on 2024-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=4)),
                ("periodo", models.CharField(blank=True, max_length=15, null=True)),
                ("anoLetivo", models.CharField(max_length=4)),
            ],
        ),
    ]
