# Generated by Django 5.0.3 on 2024-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
