# Generated by Django 5.0.3 on 2024-03-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_aluno_turma"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="turmas.turma",
            ),
        ),
    ]
