# Generated by Django 5.0.3 on 2024-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0004_remove_aluno_idade_remove_aluno_turma_aluno_bi_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="email_responsavel",
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="telef_responsavel",
            field=models.CharField(max_length=17, null=True),
        ),
    ]
