# Generated by Django 5.0.3 on 2024-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0005_aluno_email_responsavel_aluno_responsavel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="BI_No",
            field=models.CharField(
                max_length=14, null=True, unique=True, verbose_name="BI Nº"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_de_nascimento",
            field=models.DateField(null=True, verbose_name="Data de nascimento"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email",
            field=models.EmailField(
                blank=True, max_length=40, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email_responsavel",
            field=models.EmailField(
                max_length=40, null=True, verbose_name="Email do responsável"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome",
            field=models.CharField(max_length=80, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="responsavel",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telef_responsavel",
            field=models.CharField(
                max_length=17, null=True, verbose_name="Telefone do responsável"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="telefone",
            ),
        ),
    ]
