# Generated by Django 5.0.3 on 2024-03-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0006_alter_aluno_bi_no_alter_aluno_data_de_nascimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlunoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="image",
                        verbose_name="Arquivos",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos",
                        to="alunos.aluno",
                    ),
                ),
            ],
        ),
    ]
