# Generated by Django 5.0.3 on 2024-03-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anoletivo",
            name="fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anoletivo",
            name="inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
