# Generated by Django 5.0.3 on 2024-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0002_alter_anoletivo_fim_alter_anoletivo_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anoletivo",
            name="fim",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="anoletivo",
            name="inicio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
