# Generated by Django 5.0.3 on 2024-03-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0003_alter_anoletivo_fim_alter_anoletivo_inicio"),
        (
            "trimestres",
            "0004_remove_trimestre_anoletivo_remove_trimestre_fimt_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anoletivo",
            name="fim",
        ),
        migrations.RemoveField(
            model_name="anoletivo",
            name="inicio",
        ),
        migrations.AddField(
            model_name="anoletivo",
            name="trimestre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trimestres.trimestre",
            ),
        ),
    ]
