# Generated by Django 4.2.11 on 2024-03-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0004_remove_anoletivo_fim_remove_anoletivo_inicio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anoletivo",
            name="nome",
            field=models.CharField(max_length=10),
        ),
    ]
