# Generated by Django 5.0.3 on 2024-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anos_letivos", "0006_remove_anoletivo_trimestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="anoletivo",
            name="data_de_criacao",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
