# Generated by Django 5.0.3 on 2024-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("MATUTINO", "Matutino"),
                            ("VESPERTINO", "Vespertino"),
                            ("NOTURNO", "Noturno"),
                        ],
                        max_length=15,
                    ),
                ),
                ("entrada", models.CharField(max_length=15, null=True)),
                ("saida", models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
