# Generated by Django 5.0.3 on 2024-03-06 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("turnos", "0002_alter_turno_nome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="turno",
            old_name="nome",
            new_name="turno",
        ),
    ]
