# Generated by Django 5.0.3 on 2024-03-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turnos", "0003_rename_nome_turno_turno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turno",
            name="entrada",
        ),
        migrations.RemoveField(
            model_name="turno",
            name="saida",
        ),
        migrations.RemoveField(
            model_name="turno",
            name="turno",
        ),
        migrations.AddField(
            model_name="turno",
            name="cargaHo",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="turno",
            name="nome",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
