# Generated by Django 5.0.3 on 2024-03-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turnos", "0005_remove_turno_cargaho_turno_entrada_turno_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turno",
            name="nome",
            field=models.CharField(
                choices=[
                    ("MATUTINO", "Matutino"),
                    ("VESPERTINO", "Vespertino"),
                    ("NOTURNO", "Noturno"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
