# Generated by Django 5.0.3 on 2024-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="turma",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="nota",
            name="mac",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nota",
            name="np",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nota",
            name="nt",
            field=models.FloatField(),
        ),
    ]
