# Generated by Django 5.0.3 on 2024-03-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notas", "0002_nota_turma_alter_nota_mac_alter_nota_np_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="disciplina",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
