# Generated by Django 5.0.3 on 2024-03-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_aluno_turma"),
        ("disciplinas", "0001_initial"),
        ("notas", "0003_nota_disciplina"),
        ("trimestres", "0003_alter_trimestre_trimestre"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="nome_aluno",
        ),
        migrations.AddField(
            model_name="nota",
            name="aluno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="alunos.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="disciplina",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplinas.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="trimestre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trimestres.trimestre",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="turma",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="turmas.turma",
            ),
        ),
    ]
