# Generated by Django 5.0.3 on 2024-03-22 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0006_alter_aluno_bi_no_alter_aluno_data_de_nascimento_and_more"),
        ("disciplinas", "0002_disciplina_professor"),
        ("notas", "0005_alter_nota_mac_alter_nota_np_alter_nota_nt"),
        ("trimestres", "0005_trimestre_ano_letivo"),
        ("turmas", "0002_remove_turma_periodo_turma_turno_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={("aluno", "turma", "trimestre", "disciplina")},
        ),
    ]
